c      $Id$
      SUBROUTINE EARTH (XCP,X5,X6,XB,XERA,XEDC,ARA,ADC,XERD)

      IMPLICIT REAL*8 (A-H,O-Z)
	parameter (TWOPI=6.28318530717958648d0,AULT=499.004786d0)
      REAL*8 XB(3)


      AXX=XB(1)
      AYY=XB(2)
      XERA=DATAN2(AYY,AXX)
      IF (XERA.LT.0.D0) XERA=XERA+TWOPI
      AXY=XB(3)
      XERD=DSQRT(AXX**2+AYY**2+AXY**2)
      S=AXY/XERD
      XEDC=DATAN2(S,DSQRT(1.D0-S*S))
      XERD=XERD*AULT/XCP
C  CALCULATE ARRAY ELEMENTS
      X5=XERD*(DCOS(XEDC)*DSIN(ADC)*DCOS(ARA-XERA)-DSIN(XEDC)*DCOS(ADC))
      X6=XERD*DCOS(XEDC)*DCOS(ADC)*DSIN(ARA-XERA)
      RETURN
      END
