#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("infile",  help="name of input .par file")
parser.add_argument("outfile", help="name of output .par file")
parser.add_argument("-t", "--t", required=True, type=float,
                        help="time (days) added to each end of each DMX range")

args = parser.parse_args()
infile = args.infile
outfile = args.outfile
dt = args.t

f1 = open(infile,"r")
f2 = open(outfile,"w")

for s in f1:
  if s.startswith("DMXR"):
    ss = s.split()
    parname = ss[0]
    if s.startswith("DMXR1"):
      parval  = float(ss[1])-dt
    elif s.startswith("DMXR2"):
      parval  = float(ss[1])+dt
    s = "%s  %11.5f\n" % (parname, parval)
  f2.write(s)

f1.close()
f2.close()
    

